In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("D:\\Shaher\\AMIT\\Session 14 - Data visualization\\Datasets\\nba.csv")

In [39]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0

In [33]:
team = df.groupby('Team')

In [42]:
team.first()

,Name,Number,Position,Age,Height,Weight,College,Salary
Team,,,,,,,,
Atlanta Hawks,Kent Bazemore,24.0,SF,26.0,6-5,201.0,Old Dominion,2000000.0
Boston Celtics,Avery Bradley,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
Brooklyn Nets,Bojan Bogdanovic,44.0,SG,27.0,6-8,216.0,Oklahoma State,3425510.0
Charlotte Hornets,Nicolas Batum,5.0,SG,27.0,6-8,200.0,Virginia Commonwealth,13125306.0
Chicago Bulls,Cameron Bairstow,41.0,PF,25.0,6-9,250.0,New Mexico,845059.0
Cleveland Cavaliers,Matthew Dellavedova,8.0,PG,25.0,6-4,198.0,Saint Mary's,1147276.0
Dallas Mavericks,Justin Anderson,1.0,SG,22.0,6-6,228.0,Virginia,1449000.0
Denver Nuggets,Darrell Arthur,0.0,PF,28.0,6-9,235.0,Kansas,2814000.0
Detroit Pistons,Joel Anthony,50.0,C,33.0,6-9,245.0,UNLV,2500000.0
Golden State Warriors,Leandro Barbosa,19.0,SG,33.0,6-3,194.0,North Carolina,2500000.0
Houston Rockets,Trevor Ariza,1.0,SF,30.0,6-8,215.0,UCLA,8193030.0
Indiana Pacers,Lavoy Allen,5.0,PF,27.0,6-9,255.0,Temple,4050000.0
Los Angeles Clippers,Cole Aldrich,45.0,C,27.0,6-11,250.0,Kansas,1100602.0
Los Angeles Lakers,Brandon Bass,2.0,PF,31.0,6-8,250.0,LSU,3000000.0
Memphis Grizzlies,Jordan Adams,3.0,SG,21.0,6-5,209.0,UCLA,1404600.0
Miami Heat,Chris Bosh,1.0,PF,32.0,6-11,235.0,Georgia Tech,22192730.0
Milwaukee Bucks,Giannis Antetokounmpo,34.0,SF,21.0,6-11,222.0,Arizona,1953960.0
Minnesota Timberwolves,Nemanja Bjelica,88.0,PF,28.0,6-10,240.0,Louisville,3950001.0
New Orleans Pelicans,Alexis Ajinca,42.0,C,28.0,7-2,248.0,California,4389607.0
New York Knicks,Arron Afflalo,4.0,SG,30.0,6-5,210.0,UCLA,8000000.0
Oklahoma City Thunder,Steven Adams,12.0,C,22.0,7-0,255.0,Pittsburgh,2279040.0
Orlando Magic,Dewayne Dedmon,3.0,C,26.0,7-0,245.0,USC,947276.0
Philadelphia 76ers,Elton Brand,42.0,PF,37.0,6-9,254.0,Duke,947276.0
Phoenix Suns,Eric Bledsoe,2.0,PG,26.0,6-1,190.0,Kentucky,13500000.0
Portland Trail Blazers,Cliff Alexander,34.0,PF,20.0,6-8,240.0,Kansas,525093.0
Sacramento Kings,Quincy Acy,13.0,SF,25.0,6-7,240.0,Baylor,981348.0
San Antonio Spurs,LaMarcus Aldridge,12.0,PF,30.0,6-11,240.0,Texas,19689000.0
Toronto Raptors,Bismack Biyombo,8.0,C,23.0,6-9,245.0,Missouri,2814000.0
Utah Jazz,Trevor Booker,33.0,PF,28.0,6-8,228.0,Clemson,4775000.0
Washington Wizards,Alan Anderson,6.0,SG,33.0,6-6,220.0,Michigan State,4000000.0

In [50]:
grouping = df.groupby(['Team', 'Position', 'College'])

In [51]:
grouping.first()

                                                       Name  Number   Age  \
Team               Position College
Atlanta Hawks      C        Florida              Al Horford    15.0  30.0
                   PF       Bucknell           Mike Muscala    31.0  24.0
                            Louisiana Tech     Paul Millsap     4.0  31.0
                            Minnesota        Kris Humphries    43.0  31.0
                            Virginia             Mike Scott    32.0  27.0
...                                                     ...     ...   ...
Washington Wizards SF       LSU             Marcus Thornton    15.0  29.0
                   SG       Florida            Bradley Beal     3.0  22.0
                            LSU              Garrett Temple    17.0  30.0
                            Michigan State    Alan Anderson     6.0  33.0
                            Virginia Tech      Jarell Eddie     8.0  24.0

                                           Height  Weight      Salary
Team               Position College
Atlanta Hawks      C        Florida          6-10   245.0  12000000.0
                   PF       Bucknell         6-11   240.0    947276.0
                            Louisiana Tech    6-8   246.0  18671659.0
                            Minnesota         6-9   235.0   1000000.0
                            Virginia          6-8   237.0   3333333.0
...                                           ...     ...         ...
Washington Wizards SF       LSU               6-4   205.0    200600.0
                   SG       Florida           6-5   207.0   5694674.0
                            LSU               6-6   195.0   1100602.0
                            Michigan State    6-6   220.0   4000000.0
                            Virginia Tech     6-7   218.0    561716.0

[362 rows x 6 columns]